---
- name: Init {{ k14_app }}
  include_role:
      name: k14
      tasks_from: init
      apply:
          tags:
              - "{{ k14_app }}"
  tags: "{{ k14_app }}"

- name: Pull {{ k14_app }} chart
  include_role:
      name: k14
      tasks_from: chart
      apply:
          tags:
              - "{{ k14_app }}"
  tags: "{{ k14_app }}"
  when: k14_helm_repo is defined

- name: Download {{ k14_app }} chart
  include_role:
      name: k14
      tasks_from: chart-download
      apply:
          tags:
              - "{{ k14_app }}"
  tags: "{{ k14_app }}"
  when: k14_helm_server is defined


# public - site_file_contents used in later tasks
- name: Load site file for {{ k14_app }}
  include_role:
      name: k14
      tasks_from: site-file
      public: yes
      apply:
          tags:
              - "{{ k14_app }}"
  tags: "{{ k14_app }}"

- name: Process {{ k14_app }} secrets
  include_role:
      name: k14
      tasks_from: process-secrets
      apply:
          tags:
              - "{{ k14_app }}"
  tags: "{{ k14_app }}"

- name: Process {{ k14_app }} templates
  include_role:
      name: k14
      tasks_from: process-templates
      apply:
          tags:
              - "{{ k14_app }}"
  tags: "{{ k14_app }}"

# public - k14_manifest_list is used later and provided by the helm task
- name: Generate {{ k14_app }} helm template
  include_role:
      name: k14
      tasks_from: process-helm
      public: yes
      apply:
          tags:
              - "{{ k14_app }}"
  tags: "{{ k14_app }}"

- name: Apply {{ k14_app }} overlay
  include_role:
      name: k14
      tasks_from: overlay
      apply:
          tags:
              - "{{ k14_app }}"
  tags: "{{ k14_app }}"

- name: Setup {{ k14_app }} manifest folder
  include_role:
      name: k14
      tasks_from: manifest
      apply:
          tags:
              - "{{ k14_app }}"
  tags: "{{ k14_app }}"

- name: Setup {{ k14_app }} manifest folder
  include_role:
      name: k14
      tasks_from: permissions
      apply:
          tags:
              - "{{ k14_app }}"
  tags: "{{ k14_app }}"

- name: Write {{ k14_app }} scripts
  include_role:
      name: k14
      tasks_from: scripts
      apply:
          tags:
              - "{{ k14_app }}"
  tags: "{{ k14_app }}"
