---
- name: Init {{ k14.app }}
  include_role:
      name: k14
      tasks_from: init
      apply:
          tags:
              - "{{ k14.app }}"
  tags: "{{ k14.app }}"

- name: Pull {{ k14.app }} repo
  include_role:
      name: k14
      tasks_from: git-repo
      apply:
          tags:
              - "{{ k14.app }}"
  tags: "{{ k14.app }}"
  when: (k14.helm_repo is defined) or
        (k14.kompose_repo is defined)

- name: Download {{ k14.app }} chart
  include_role:
      name: k14
      tasks_from: chart-download
      apply:
          tags:
              - "{{ k14.app }}"
  tags: "{{ k14.app }}"
  when: k14.helm_server is defined


# public - site_file_contents used in later tasks
- name: Load site file for {{ k14.app }}
  include_role:
      name: k14
      tasks_from: site-file
      public: yes
      apply:
          tags:
              - "{{ k14.app }}"
  tags: "{{ k14.app }}"

- name: Process {{ k14.app }} secrets
  include_role:
      name: k14
      tasks_from: process-secrets
      apply:
          tags:
              - "{{ k14.app }}"
  tags: "{{ k14.app }}"

- name: Process {{ k14.app }} templates
  include_role:
      name: k14
      tasks_from: process-templates
      apply:
          tags:
              - "{{ k14.app }}"
  tags: "{{ k14.app }}"

# public - k14_manifest_list is used later
- name: Generate {{ k14.app }} helm manifest
  include_role:
      name: k14
      tasks_from: process-helm
      public: yes
      apply:
          tags:
              - "{{ k14.app }}"
  tags: "{{ k14.app }}"
  when: (k14.helm_repo is defined) or
        (k14.helm_server is defined)

# public - k14_manifest_list is used later
- name: Generate {{ k14.app }} kompose manifest
  include_role:
      name: k14
      tasks_from: process-kompose
      public: yes
      apply:
          tags:
              - "{{ k14.app }}"
  tags: "{{ k14.app }}"
  when: k14.kompose_repo is defined

- name: Apply {{ k14.app }} overlay
  include_role:
      name: k14
      tasks_from: overlay
      apply:
          tags:
              - "{{ k14.app }}"
  tags: "{{ k14.app }}"

- name: Setup {{ k14.app }} manifest folder
  include_role:
      name: k14
      tasks_from: manifest
      apply:
          tags:
              - "{{ k14.app }}"
  tags: "{{ k14.app }}"

- name: Setup {{ k14.app }} manifest folder permissions
  include_role:
      name: k14
      tasks_from: permissions
      apply:
          tags:
              - "{{ k14.app }}"
  tags: "{{ k14.app }}"

- name: Write {{ k14.app }} scripts
  include_role:
      name: k14
      tasks_from: scripts
      apply:
          tags:
              - "{{ k14.app }}"
  tags: "{{ k14.app }}"
