- name: debug parent_role_path
  debug: var=ansible_parent_role_paths
  tags: [never, debug]

- name: find secrets templates
  stat:
      path: "{{ secrets_item }}" 
  register: k14_secrets_list
  loop: "{{ query('filetree', '{{ ansible_parent_role_paths[1] }}/files/secrets/') }}"
  loop_control:
      label: "{{secrets_item.path}}"
      loop_var: "secrets_item"
  when: secrets_item.state == 'file'

- name: debug secrets list
  debug: var=k14_secrets_list
  tags: [never, debug]

- name: "Process ytt secrets"
  shell: "{{ lookup('template', 'ytt-secrets.sh') }}"
  when: k14_secrets_list.skipped is not defined

